### ISSUE TITLE
How to work with Chinese？

### ISSUE THREAD

**Issue by SmileSmith** [liyucheng09/Selective_Context#1]
When select Chinese content result is something like bytes:\x8a
<img width="1491" alt="image" src="https://user-images.githubusercontent.com/17798955/236389505-396aa5ea-bbe4-4ef2-a9a8-ef4d1262ea75.png">

**Comment by liyucheng09** [comment]
Now you can specify the language you're working on. Choose `zh` to switch the base model from `gpt2` to `uer/gpt2-chinese-cluecorpussmall`. Bug fixed.
