### ISSUE TITLE
Problem with sentence level reduction

### ISSUE THREAD

**Issue by pengshancai** [liyucheng09/Selective_Context#15]
It seems when I attempted to do sentence-level reduction, the variable self.keep_leading_word, self.num_lead_words and self.mask_token were never declared. Any clarification? Thanks!

**Comment by liyucheng09** [comment]
any error message?

**Comment by pengshancai** [comment]
Guess I figured it out. 
Your file selective_context.py in the GitHub repo is different from the selective_context.py in the pip install version. 
If you look at the selective_context.py in this GitHub repo you will find that some variables (e.g. self.keep_leading_word) were used without declaration.

Also, it seems some libs installed together with your package are out of date. (e.g. spacy) and are not compatible with other packages.

**Comment by liyucheng09** [comment]
see [this](https://github.com/liyucheng09/Selective_Context/blob/main/src/selective_context/__init__.py#L52)).

```
class SelectiveContext:

    def __init__(self, model_type = 'gpt2', lang = 'en'):

        self.model_type = model_type
        self.lang = lang
        self.device = DEVICE

        # this means we calculate self-information sentence by sentence
        self.sent_level_self_info = True

        self._prepare_phrase_tokenizer()
        self.sent_tokenize_pattern = r"(?<!\w\.\w.)(?<![A-Z][a-z]\.)(?<=\.|\?)\s"
        self.phrase_mask_token = ''
        self.sent_mask_token = "<...some content omitted.>"
        self.keep_leading_word = False
        self.mask_token = ''
        self._prepare_model()
```

I don't see any undeclared parameters here? What error you found exactly?

please share more info for me to improve this project, in case other users find it helpful.

**Comment by pengshancai** [comment]
The undeclared variable is in this file: https://github.com/liyucheng09/Selective_Context/blob/main/selective_context.py

**Comment by liyucheng09** [comment]
I see. Thanks! Would you mind open a pr for this if you already solve it?

**Comment by liyucheng09** [comment]
Never mind, issue solved.
