### ISSUE TITLE
How to use llama or llama2 to compress text

### ISSUE THREAD

**Issue by www-Ye** [liyucheng09/Selective_Context#19]
How can I use LLaMA or LLaMA2 to compress text? Using the LLaMA2 tokenizer directly results in compressed text without any spaces. Can you make public the code used in your experiments with the LLaMA family for compression? Thank you very much!
![image](https://github.com/liyucheng09/Selective_Context/assets/51852529/e7b0dc94-fafd-482b-9abd-10803e19312e)

**Comment by www-Ye** [comment]
When I modify the code from `sent = ''.join(tokens)` to `sent = ' '.join(tokens)`, the resulting text has very unnatural spacing, such as 'LLaMA' turning into 'L La MA'.
![image](https://github.com/liyucheng09/Selective_Context/assets/51852529/a9ec3c61-89e8-4ecb-bb8b-e0056c5e340d)

**Comment by liyucheng09** [comment]
I just made a new commit that add the support for llama2 for self-information computing, check [here](https://github.com/liyucheng09/Selective_Context/blob/main/selective_context.py#L119).

Remember to keep using `sent = ''.join(tokens)`.

**Comment by www-Ye** [comment]
Thank you for your prompt response! However, when executing the code, I noticed that the part `.replace('_', ' ')` should actually be `.replace('▁', ' ')` to replace a slightly different underscore character. After using `.replace('▁', ' ')`, everything worked normally.
![image](https://github.com/liyucheng09/Selective_Context/assets/51852529/9008f501-bcbf-40cd-b799-8c2da6c217a6)
![image](https://github.com/liyucheng09/Selective_Context/assets/51852529/6fea3e03-c812-47a6-915b-c0ffd6df4a14)

**Comment by liyucheng09** [comment]
Thanks. Now the problems solved.
