### ISSUE TITLE
AttributeError: 'SelectiveContext' object has no attribute 'keep_leading_word'

### ISSUE THREAD

**Issue by SimFG** [liyucheng09/Selective_Context#3]
In the huggingface demo, when i choose the `sent` reduce level, the error occurs.

prompt: `user: What is the meaning of life? Explain it in 5 paragraphs. `

![image](https://user-images.githubusercontent.com/21985684/236622486-e4226594-6bb7-40bd-99f5-beec80656e77.png)

**Comment by liyucheng09** [comment]
bug fixed. But you might encounter the [410 error](https://discuss.huggingface.co/t/connection-failed-with-status-410/30357) from Hugging face side. It seems reopen with a private window can work like a charm.
